version: '3.3'

networks:
  default:
    external:
      name: research-coder

services:

  rc-users:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    environment:
      RABBITMQ_HOST: rabbitmq
      MYSQL_HOST: mysql
      MYSQL_DB: rc_users
      MYSQL_USER: root
      MYSQL_PASS: secret
    ports:
      - 8080:80

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: rc_users

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"